* Athens EuRuKo 2013 Mission Statement
  Essence of our organisation goals and the philosophies underlying them. 
  What our business is all about us, attendees, suppliers, community
  
- What is Euruko
  EuRuKo is an annual European conference about the Ruby ecosystem,
  each year organised in a different European city, aiming at bringing
  together individuals, organisations, companies and the community at large. 
  Participants from all over the world gather for 2 exciting days full
  of cutting edge technology presentations, best Ruby practices,
  intriguing techniques and networking. EuRuKo is all about promoting
  Ruby technology and fostering the community ties in an individual as
  well as in a collective level.
  
- What is Ruby
  Ruby, an exciting, powerful, highly productive and mature
  programming language used by thousands of programmers and companies,
  is celebrating its birthday in 2013 and what better way to do it
  than releasing a brand new version alongside a new version of Rails,
  its showcase tool.

- Why are we organising this event
  It's a unique opportunity for us to be involved in the 

- What’s in it for the committee

- What’s in it for the sponsors, foreign and local?

- What’s in it for the local community, country, greek professional sector

- Where is the money


Στην ανάπτυξη της τοπικής κοινότητας προγραμματιστών της γλώσσας αυτής
Στην ενδυνάμωση της επικοινωνίας μεταξύ της τοπικής κοινότητας προγραμματιστών και της παγκόσμιας
Στην προβολή της τοπικής τεχνολογικής κοινότητας στο εξωτερικο
Στην προβολή της γλώσσας σε εκπαιδευτικούς φορείς της χώρας
Στην ενδυνάμωση των σχέσεων μεταξύ των εταιριών του κλάδου και των μελλών της κοινότητας

